apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: web-rs
  labels:
    tier: front
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: front
  template:
    metadata:
      name: nginx-podf
      labels:
        tier: front
    spec:
      containers:
      - name: nginx
        image: nginx